---
- hosts: default
- name: clone application repo
  hosts: default
  become: true

  tasks:
    - name: Ensure the remote directory exists
      file:
        path: "{{ target_directory }}"
        state: directory

    - name: Ensure the remote key directory exists
      file:
        path: "{{ remote_key_path }}"
        state: directory

    - name: Download ssh keys from s3 bucket
      aws_s3:
        aws_access_key: "{{ access_key }}" 
        aws_secret_key: "{{ secret_key }}"
        bucket: musipedia-secretes
        object: "{{ private_key }}"
        mode: get
        dest: "{{ remote_key_path }}/{{ private_key }}"

    - name: Modify private key permission
      command: "chmod 400 {{ remote_key_path }}/{{ private_key }}"


- name: Clone Application Repository
  hosts: default
  become: true

  tasks:
    - name: Ensure the target directory exists
      file:
        path: "{{ target_directory }}"
        state: directory

    - name: Clone the GitHub repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ target_directory }}"
        version: "main"
        accept_hostkey: yes
        key_file: "{{ remote_key_path }}/{{ private_key }}"

    - name: Download the env file from s3 bucket
      aws_s3:
        aws_access_key: "{{ access_key }}" 
        aws_secret_key: "{{ secret_key }}"
        bucket: musipedia-secretes
        object: "{{remote_env_file}}"
        mode: get
        dest: "{{target_directory}}/{{remote_env_file}}"

    - name: Change ownership of the target directory
      ansible.builtin.command:
        cmd: "sudo chown -R $USER:$USER {{ target_directory }}"

    - name: Install application dependencies
      ansible.builtin.shell:
        cmd: "npm install"
        chdir: "{{ target_directory }}"

  
