---
- hosts: default
- name: Start the application
  hosts: default
  become: true

  tasks:
    - name: start app
      ansible.builtin.shell:
        cmd: "npm start"
        chdir: "{{ target_directory }}"
