---
- hosts: aws_ec2
- name: Start the application
  hosts: aws_ec2
  become: true

  tasks:
    - name: start app
      ansible.builtin.shell:
        cmd: "npm start"
        chdir: "{{ target_directory }}"
