---
- hosts: default
- name: Install Node.js and npm
  hosts: default
  become: true

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    
    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present


    - name: Install Python
      ansible.builtin.package:
        name: python3
        state: present

    - name: Install pip
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install boto3 library
      ansible.builtin.pip:
        name: boto3
        state: present

    - name: Install packaging.version Python module
      pip:
        name: packaging
        state: present


    
