name: Packer and Terraform Provision

on:
  push:
    branches:
      - ganga
  workflow_dispatch:

jobs:

  provision-terraform:
    runs-on: ubuntu-latest
    needs: provision-packer
    env:
      # TF_VAR_awskey01: ${{ secrets.ssh_private_key }}
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        id: setupterraform

      - name: Terraform Init
        id: initailizeterraform
        run: terraform init -migrate-state
        working-directory: ./devops/terraform/

      - name: Format Terraform
        id: formatterraform
        run: terraform fmt
        working-directory: ./devops/terraform/

      - name: Validate Terraform
        id: validateterraform
        run: terraform validate
        working-directory: ./devops/terraform/

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false
        working-directory: ./devops/terraform/

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./devops/terraform/