name: Packer and Terraform Provision

on:
  push:
    branches:
      - ganga
  workflow_dispatch:

jobs:
  provision-packer:
    runs-on: ubuntu-latest
    env:
      access_key: ${{ secrets.ACCESS_KEY }}
      secret_key: ${{ secrets.SECRET_KEY }}
      region: ${{ secrets.REGION }}
      source_ami: ${{ secrets.SOURCE_AMI }}
      instance_type: ${{ secrets.INSTANCE_TYPE }}
      ssh_user: ${{ secrets.SSH_USER }}
      project_name: ${{ secrets.PROJECT_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Packer
        id: setup
        uses: hashicorp/setup-packer@main

      - name: Initialize Packer
        id: initpacker
        run: packer init ./devops/packer/

      - name: Format Packer
        id: fmtpacker
        run: packer fmt ./devops/packer/

      - name: Validate Packer
        id: validate
        run: |
          access_key=$ACCESS_KEY \
          secret_key=$SECRET_KEY \
          region=$REGION \
          source_ami=$SOURCE_AMI \
          instance_type=$INSTANCE_TYPE \
          ssh_user=$SSH_USER \
          project_name=$PROJECT_NAME \
          packer validate ./devops/packer/

      - name: Build Image
        id: build
        run: packer build -var-file="./devops/packer/variable.json" ./devops/packer/packer.json   

  provision-terraform:
    runs-on: ubuntu-latest
    needs: provision-packer
    env:
      # TF_VAR_awskey01: ${{ secrets.ssh_private_key }}
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        id: setupterraform

      - name: Terraform Init
        id: initailizeterraform
        run: terraform init -migrate-state
        working-directory: ./devops/terraform/

      - name: Format Terraform
        id: formatterraform
        run: terraform fmt
        working-directory: ./devops/terraform/

      - name: Validate Terraform
        id: validateterraform
        run: terraform validate
        working-directory: ./devops/terraform/

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false
        working-directory: ./devops/terraform/

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./devops/terraform/